### PR TITLE
[wip] Fix numpy min for 3.8->3.9

### PR DESCRIPTION
**Pull request by IAlibay**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by IAlibay** [comment]
@conda-forge-admin, please rerender

**Comment by IAlibay** [comment]
@conda-forge-admin, please rerender

**Review by orbeckst — APPROVED** [review]
ok, let's try it

Do we have an open issue in MDA that should be referencing this PR?

**Comment by IAlibay** [comment]
please wait on merge @orbeckst - the migration pin isn't working

**Comment by orbeckst** [comment]
Sure, I assigned the PR to you so please be in charge. 

I just signed off on your fix to put in a working numpy version.

**Comment by IAlibay** [comment]
It's also worth the discussion of why this happens with CF and if we actually want to do this (technically it's expected behaviour I think) - I'll update the first comment with details once I fix py3.11

**Review by hmacdope — APPROVED** [review]
LGTM

**Comment by hmacdope** [comment]
@IAlibay feel free to merge when your happy. :)

**Comment by IAlibay** [comment]
Ok, I've kind of hit a wall on the pinning here, primarily because hacking together a solution for a migration (py3.11) is just not a simple thing. I've spoke to a few folks more knowledgeable than me on this and the gains don't seem to be worth it.

I'm also not addressing the pypy builds for the same reason.

I'm going to address what's going on here in this comment and we can discuss if folks want to go ahead with it or not.

## Why is this happening?

The plain answer is that the pinning used by conda-forge don't go down to the bugfix level and numpy builds aren't backwards compatible with each other between bugfix levels either. I.e. the dependencies required for numpy 1.20.3 don't allow you to just swap out to 1.20.0.

As a result, we end up with builds that just require the use of the latest bugfix of whatever minor version we've pinned to.

## Is this an issue?

Yes and no.

Technically it's annoying that we can't guarantee that the exact minimum version identified in the pyproject.toml will be supported by conda-forge. However, conda-forge is usually treated as a package manager that doesn't _have_ to adhere to such limits. Generally if it's hand wavily in the right ballpark then you're doing fine.

## Recommendation

I would probably recommend going with a bugfix level pin here just because it makes things a tad bit easier. That being said it's going to have to be a bit inconsistent because py3.11 can't be pinned in the same way right now (it'll default to a minimum of numpy 1.23.5 I think).

Thoughts @hmacdope @orbeckst @richardjgowers ?

**Comment by IAlibay** [comment]
> @IAlibay feel free to merge when your happy. :)

P.S. I can't merge, I'm not an admin on this feedstock.

**Comment by orbeckst** [comment]
I am not overly worried if the minimal numpy version is marginally increased for the conda package. It simply says that if you want to use the package in a conda context then that's what you have to do. If you can build from source or pip then you may be able to shave off a few versions if you really need it.

As such I'd simply say let's go ahead.

I think you should also be a code owner/admin on this repo, @IAlibay — how can we add you?

**Comment by hmacdope** [comment]
Thanks for your wonderful help @IAlibay I trust your judgement. Tbh distopia itself has no real reliance on any specific Numpy version IIRC so should be ok to be in the right ballpark.

**Comment by IAlibay** [comment]
> I think you should also be a code owner/admin on this repo, @IAlibay — how can we add you?

I think the usual approach is just to do this: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by hmacdope** [comment]
> > I think you should also be a code owner/admin on this repo, @IAlibay — how can we add you?
> 
> 
> 
> I think the usual approach is just to do this: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

Done.

**Comment by IAlibay** [comment]
@conda-forge-admin, please rerender

**Review by richardjgowers — APPROVED** [review]

**Comment by IAlibay** [comment]
hopefully this fixes the mypy issues downstream

**Pull request merged**
